name: hinjaku_honyaku_app
description: The Hinjaku Honyaku app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  http: ^0.12.1
  flutter_html: ^0.11.1
  flutter_hooks: ^0.9.0
  provider: ^4.0.5+1
  intl: ^0.16.1
  sliding_sheet: ^0.3.5
  auto_route: ^0.4.5
  flutter_speed_dial: ^1.2.5
  url_launcher: ^5.4.5
  xlive_switch: ^1.0.5
  animations: ^1.0.0+5
  shared_preferences: ^0.5.7+1
  google_fonts: ^1.1.0
  firebase_messaging: ^6.0.13
  delayed_display: ^1.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.4.8
  flutter_launcher_icons: ^0.7.5
  build_runner: ^1.9.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/HH.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "dev_assets/HH-adaptive.png"
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - google_fonts/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Hazard
      fonts:
        - asset: lib/view/fonts/Hazard.otf
    - family: Lato
      fonts:
        - asset: google_fonts/Lato-Regular.ttf
        - asset: google_fonts/Lato-Bold.ttf
          weight: 700
        - asset: google_fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: google_fonts/Lato-Italic.ttf
          style: italic
        - asset: google_fonts/Lato-Black.ttf
          weight: 900
        - asset: google_fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
    - family: NotoSerif
      fonts:
        - asset: google_fonts/NotoSerif-Regular.ttf
        - asset: google_fonts/NotoSerif-Bold.ttf
          weight: 700
        - asset: google_fonts/NotoSerif-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: google_fonts/NotoSerif-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
